#if !canImport(ObjectiveC)
import XCTest

extension URLExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLExtensionsTests = [
        ("testAppendingPathComponents", testAppendingPathComponents),
        ("testAppendingPathComponents2", testAppendingPathComponents2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(URLExtensionsTests.__allTests__URLExtensionsTests),
    ]
}
#endif
