#if !canImport(ObjectiveC)
import XCTest

extension FileManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileManagerTests = [
        ("testFileExistsAtURL", testFileExistsAtURL),
    ]
}

extension FolderManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FolderManagerTests = [
        ("testCopy", testCopy),
        ("testFailure", testFailure),
        ("testFile", testFile),
        ("testFolder", testFolder),
        ("testForEach", testForEach),
        ("testForEachWibble", testForEachWibble),
        ("testHidden", testHidden),
        ("testNoThrowCopy", testNoThrowCopy),
        ("testNoThrowFailure", testNoThrowFailure),
        ("testNoThrowFile", testNoThrowFile),
        ("testNoThrowFolder", testNoThrowFolder),
        ("testNoThrowForEach", testNoThrowForEach),
        ("testTypePropogation", testTypePropogation),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("testAppendingPathComponents", testAppendingPathComponents),
        ("testAppendingPathComponents2", testAppendingPathComponents2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FileManagerTests.__allTests__FileManagerTests),
        testCase(FolderManagerTests.__allTests__FolderManagerTests),
        testCase(URLTests.__allTests__URLTests),
    ]
}
#endif
